### ISSUE TITLE
Possible issue with fail deprecate mode.

### ISSUE THREAD

**Issue by joeHillman** [salesforce-ux/sass-deprecate#14]
Hello, cool project!
Looking to setup on our application.

Outline of my setup is below.
Figured I'd put the potential issue first.

There's a potential issue with the deprecate mode fail.
The following snippets are returned on different modes...

---
- Sensible

```
Running "sass:common" (sass) task
WARNING: Deprecated code was found, it should be removed before its release.
REASON:  Use .btn-primary-2-0-0 instead.
Backtrace:
    vendor/bower/sass-deprecate/index.scss:159, in mixin `deprecate`
    src/script/li/stylesheets/scss/_button.scss:59


Done, without errors.
```

---
- Verbose

```
Running "sass:common" (sass) task
WARNING: Some code will be deprecated in 2.0.0. Current version: 2.0.0.
Backtrace:
    vendor/bower/sass-deprecate/index.scss:119, in mixin `deprecate`
    src/script/li/stylesheets/scss/_button.scss:59

WARNING: Deprecated code was found, it should be removed before its release.
REASON:  Use .btn-primary-2-0-0 instead.
Backtrace:
    vendor/bower/sass-deprecate/index.scss:159, in mixin `deprecate`
    src/script/li/stylesheets/scss/_button.scss:59


Done, without errors.
```

---
- Fail

```
Running "sass:common" (sass) task
>> Error: Deprecated code was found. Remove it to continue.
>>        REASON:  Use .btn-primary-2-0-0 instead.
>>         on line 157 of vendor/bower/sass-deprecate/index.scss
>> >>           @error 'Deprecated code was found. Remove it to continue.#{$message}
>>    ----------^
Warning:  Use --force to continue.

Aborted due to warnings.
```

The output the Fail provides I would have expected to point to the offending code in the source of the project, not so much the sass-deprecation index, though I may be wrong here.

---
- My setup as outlined here

```
@import "base"; // importing vars for btn-primary
@import "index";

$app-version: '2.0.0';
$deprecate-mode: 'verbose';

$btn-primary-bg-2-0-0: #333;
$btn-primary-text-color-2-0-0: #ccc;
$btn-primary-border-color-2-0-0: #333;

@include deprecate('2.0.0', 'Use .btn-primary-2-0-0 instead.') {
  .btn-primary {
    @include button-type($btn-primary-bg, $btn-primary-text-color, $btn-primary-border-color);
    &:hover {
      color: $btn-primary-text-color;
    }
  }
}
.btn-primary-2-0-0 {
  @include button-type($btn-primary-bg-2-0-0, $btn-primary-text-color-2-0-0, $btn-primary-border-color-2-0-0);
  &:hover {
    color: $btn-primary-text-color;
  }
}
```

**Comment by joeHillman** [comment]
The silent mode will not output any code that is not slated for deprecation.
I didn't raise an issue though as I didn't see any if/else blocks on the index file that might handle the silent mode. Wanted to point this out anyways in the event it was overlooked.

**Comment by kaelig** [comment]
Thanks, @joeHillman, good catch!

Unfortunately, it seems that in Sass, throwing an `@error` points to the error itself, instead of pointing to the place the mixin was called.

Would it be more useful for developers if there were both a warning (that would point to the correct place) and an error?

**Comment by joeHillman** [comment]
@kaelig , I ran thru it again this morning...
The error message that points to the error itself, I wouldn't see useful from a developer perspective unless the developer was supporting the deprecate library itself. That said, I guess it would be useful for those who might alter the deprecate library for their purposes and I could see it being useful to report possible issues though to those whom do support it outright.

For my intents, I'm pulling it in with Bower and wouldn't have much cause to make changes on the deprecate code itself. As the output stands, it points to the deprecate index.scss and L# on warning cases alongside the SCSS that is slated for deprecation, on all modes except for fail.

I wouldn't see any harm with leaving the error in, that points to the deprecate index file especially where that's default behavior but I would certainly see the warning for deprecated SCSS and the pointer as essential for a developer so they would know what needs to be updated.

One could argue if you setup a separate version variable in the end users codebase to interpolate in the CSS class, it would be easy enough for a find thru the IDE, but that might be a bit of an opinionated decision to make for anothers' project.

Thanks for giving that a look and I'm looking forward to seeing the progress on this project.

**Comment by kaelig** [comment]
For now we're not using the "fail" mode at Salesforce but feel free to open a Pull Request!

**Comment by kaelig** [comment]
Closing this as no PR was opened.
